spring:
  application:
    name: demo

  graphql:
    graphiql:
      enabled: true

  datasource:
    url: jdbc:h2:mem:bookdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-servers: localhost:29092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

camel:
  component:
    kafka:
      brokers: localhost:29092

grpc:
  server:
    port: 9090
  client:
    simple:
      address: static://localhost:9090
      enableKeepAlive: true

logging:
  level:
    org.springframework.security: DEBUG