spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 109513544406-ue87p4fn9bov1remrkp53nsspp3p49fk.apps.googleusercontent.com
            client-secret:
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
server:
  port: 8080